[build]
target = "i386-unknown-none.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem", "panic-unwind"]

[registries.crates-io]
protocol = "sparse"
